/*
 * Code generated by MIMOS tool.
 * Date: 2024/03/13 20:03:26
 * 
 * Read laser data from the given log file, which is used for sensor motion.
 * 
 * Outputs: 
 * Current laser log, a list of float, which has 180 elements.
 */

import java.util.Random;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.ArrayList;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class Laser_Rangefinder {
    /* Inputs: */

    /* Outputs: */
    float[] output1;

    List<float[]> container = new ArrayList<>();
    static String filePath = "D:\\lxx\\thesis\\cases\\lxx\\pfl0312\\data\\logs\\log1.txt";
    static int lineNumber = 1;
    static int logLength = 0; // The number of logs in the file

    public Laser_Rangefinder() {
        String line = "";
        String splitBy = " ";
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            while ((line = br.readLine()) != null) {
                String[] dataVal = line.split(splitBy);
                float[] inp = new float[180];
                for (int i = 0; i < 180; i++) {
                    inp[i] = Float.valueOf(dataVal[3 + i]);
                }
                container.add(inp);
                logLength++;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /* Node computation: */
    public boolean run() {

        if (lineNumber < logLength) {
            output1 = container.get(lineNumber);
            System.out.println("laser Output: line: " + lineNumber + ". ");
        } else {
            output1 = container.get(logLength - 1);
            System.out.println("Laser: There only " + logLength + "logs. No new log data any more.");
        }
        lineNumber++; // Update the lineNumber for the next read

        // System.out.println("logLength: " + logLength);
        // System.out.print("-> Log data: laserLog: ");
        // if (output1 != null && output1.length != 0) {
        //     for (int i = 0; i < 180; i++) {
        //         System.out.print(output1[i] + " ");
        //     }
        // } else {
        //     System.out.print("null");
        // }


        return true;
    }

    /* Setters (for inputs): */

    /* Getters (for outputs): */
    public float[] get_output1() {
        return output1;
    }
}
