/*
 * Code generated by MIMOS tool.
 * Date: 2024/04/12 12:14:10
 * Windows:
 * PS D:\lxx\thesis\Cpp-Integeration\code> g++ -I"C:\Users\lxx04\.jdks\jdk-17\include" -I"C:\Users\lxx04\.jdks\jdk-17\include\win32" -shared -fPIC -o libmyNativeLibrary.dll Sum.cpp
 */

import java.util.Random;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.ArrayList;
import java.util.*;
import java.io.*;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//import java.lang.reflect.Field;



public class Sum
{
    //private final static Logger logger = LoggerFactory.getLogger(Sum.class);
    /* Inputs:  */
    double input2;
    double input1;

    /* Outputs:  */
    double output1;

       // Declare the native method
    public static native double myNativeSum(double a, double b);
    
    public Sum(){
        System.load("D:\\lxx\\thesis\\Cpp-Integeration\\code\\libmyNativeLibrary.dll");    
    }

    /* Node computation: */
    public boolean run() {
        // TODO: put your code here
        try{
            output1 = myNativeSum(input1, input2);
        }catch(Exception exp){
            exp.printStackTrace();
        }
        return true;
    }

    /* Setters (for inputs): */
    public void set_input2(double i) {
        input2 = i;
    }
    public void set_input1(double i) {
        input1 = i;
    }

    /* Getters (for outputs): */
    public double get_output1() {
        return output1;
    }
}
