/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sum */

#ifndef _Included_Sum
#define _Included_Sum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sum
 * Method:    myNativeMethod
 * Signature: ()V
 */
JNIEXPORT jdouble JNICALL Java_Sum_myNativeSum
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
