/*
 * Code generated by MIMOS tool.
 * Date: 2024/04/08 09:19:44
 */

import java.util.Random;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.ArrayList;
import java.util.*;

public class Node_1
{
    /* Inputs:  */

    /* Outputs:  */
    double[] output1;

    /* Node computation: */
    public boolean run() {
        output1 = new double[3];
        // The current state of the robot
        output1[0] = 30.0;
        output1[1] = 1.0;
        output1[2] = 1.0;
        return true;
    }

    /* Setters (for inputs): */

    /* Getters (for outputs): */
    public double[] get_output1() {
        return output1;
    }
}
