/*
 * Code generated by MIMOS tool.
 * Date: 2024/05/05 14:50:46
 */

import java.util.Random;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.ArrayList;
import java.util.*;


public class Display
{
    /* Inputs:  */
    double input1;

    /* Outputs:  */
    double output1;

    /* Node computation: */
    public boolean run() {
        output1 = input1;
        return true;
    }

    /* Setters (for inputs): */
    public void set_input1(double i) {
        input1 = i;
    }

    /* Getters (for outputs): */
    public double get_output1() {
        return output1;
    }
}